export const documentationStyles = `:root { color-scheme: light; --ink:#17212b; --muted:#566371; --line:#d8dee5; --paper:#fff; --wash:#f4f7f9; --accent:#075985; --accent2:#0f766e; }
* { box-sizing:border-box; } body { margin:0; color:var(--ink); background:var(--wash); font:16px/1.65 system-ui,-apple-system,Segoe UI,sans-serif; }
a { color:var(--accent); text-decoration-thickness:.08em; text-underline-offset:.15em; } code { font: .9em ui-monospace,SFMono-Regular,Consolas,monospace; background:#eef3f6; padding:.08rem .28rem; border-radius:.2rem; }
.site-header { background:#102a3a; color:white; border-bottom:4px solid #14b8a6; } .site-header__inner { width:100%; margin:auto; padding:.75rem 1rem; display:flex; align-items:center; gap:1.25rem; }
.brand { color:white; text-decoration:none; font-weight:760; letter-spacing:.01em; white-space:nowrap; } .primary-nav { display:flex; flex-wrap:wrap; gap:.35rem .55rem; align-items:center; } .primary-nav a { color:#dceef6; }
.nav-group { position:relative; } .nav-group summary { color:#dceef6; cursor:pointer; list-style:none; padding:.28rem .52rem; border:1px solid transparent; border-radius:.25rem; } .nav-group summary::-webkit-details-marker { display:none; } .nav-group summary::after { content:" ▾"; color:#7dd3c7; } .nav-group[open] summary { border-color:#426477; background:#173c50; } .nav-group__menu { position:absolute; z-index:20; top:calc(100% + .35rem); left:0; min-width:14.5rem; padding:.45rem; border:1px solid #557788; border-radius:.3rem; background:#102a3a; box-shadow:0 16px 32px #07182166; display:grid; } .nav-group__menu a { padding:.42rem .55rem; text-decoration:none; border-radius:.2rem; } .nav-group__menu a:hover,.nav-group__menu a:focus { background:#1a485f; color:white; }
.page { width:100%; margin:1rem 0; padding:0 .75rem; } .page__panel { background:var(--paper); padding:1rem clamp(.75rem,1.5vw,1.5rem); border:1px solid var(--line); box-shadow:0 8px 24px #17304212; }
.content { max-width:100%; } .content > p,.content > ul,.content > ol { max-width:none; } h1 { font-size:clamp(2rem,5vw,3.3rem); line-height:1.1; margin:.25rem 0 1.5rem; } h2 { margin-top:2.5rem; line-height:1.25; } h3 { margin-top:1.75rem; }
.lead { font-size:1.18rem; color:#334554; } .kicker { color:var(--accent2); text-transform:uppercase; letter-spacing:.11em; font-size:.76rem; font-weight:800; } .breadcrumb { display:flex; gap:.55rem; color:var(--muted); font-size:.88rem; }
.section-nav { display:flex; flex-wrap:wrap; align-items:center; gap:.35rem .8rem; border-block:1px solid var(--line); padding:.65rem 0; margin:0 0 1.4rem; font-size:.88rem; } .section-nav span { color:var(--muted); font-weight:750; } .section-nav a { white-space:nowrap; }
.callout { max-width:none; border-left:4px solid #14b8a6; background:#ecfdf9; padding:.8rem 1rem; margin:1.25rem 0; } pre { overflow:auto; background:#102a3a; color:#e8f3f7; padding:.8rem 1rem; border-radius:.35rem; } pre code { background:transparent; padding:0; color:inherit; }
.source-file { margin:1rem 0; border:1px solid var(--line); border-radius:.35rem; background:#f8fafb; } .source-file summary { cursor:pointer; padding:.6rem .75rem; font-weight:650; } .source-file pre { margin:0; border-radius:0 0 .35rem .35rem; max-height:48rem; }
.artifact-browser { margin:1.25rem 0 2rem; border:1px solid #9bb5c2; border-radius:.45rem; overflow:hidden; background:#f8fafb; } .artifact-browser__tabs { display:flex; flex-wrap:wrap; gap:.25rem; padding:.4rem .5rem 0; background:#e7f0f4; border-bottom:1px solid #9bb5c2; } .artifact-browser__tabs button { appearance:none; border:1px solid transparent; border-bottom:0; border-radius:.35rem .35rem 0 0; background:transparent; color:#294859; padding:.45rem .75rem; font:inherit; font-weight:750; cursor:pointer; } .artifact-browser__tabs button[aria-selected="true"] { background:white; color:var(--accent); border-color:#9bb5c2; transform:translateY(1px); } .artifact-browser__body { display:grid; grid-template-columns:minmax(13rem,24%) minmax(0,1fr); min-height:34rem; } .artifact-browser__inventory { padding:.5rem; border-right:1px solid var(--line); background:#f3f7f9; overflow-x:hidden; overflow-y:auto; } .artifact-browser__files { display:grid; gap:.25rem; } .artifact-browser__files button { width:100%; border:1px solid transparent; border-radius:.25rem; background:transparent; padding:.42rem .48rem; text-align:left; cursor:pointer; overflow-wrap:anywhere; } .artifact-browser__files code { white-space:normal; overflow-wrap:anywhere; word-break:break-word; } .artifact-browser__files button:hover,.artifact-browser__files button:focus { border-color:#9bb5c2; background:white; } .artifact-browser__files button[aria-current="true"] { border-color:#0f766e; background:#e8faf6; } .artifact-browser__viewer { min-width:0; background:#102a3a; color:#e8f3f7; } .artifact-browser__path { margin:0; min-height:2.4rem; padding:.5rem .75rem; border-bottom:1px solid #426477; color:#bde9df; font: .82rem ui-monospace,SFMono-Regular,Consolas,monospace; overflow-wrap:anywhere; word-break:break-word; } .source-file pre,.artifact-browser__viewer pre { overflow-x:hidden; overflow-y:auto; white-space:pre-wrap; overflow-wrap:anywhere; word-break:break-word; } .source-file pre code,.artifact-browser__viewer pre code { white-space:inherit; overflow-wrap:inherit; word-break:inherit; } .artifact-browser__viewer pre { margin:0; max-height:56rem; border-radius:0; } .artifact-browser template { display:none; }
table { border-collapse:collapse; width:100%; margin:1rem 0 2rem; font-size:.94rem; } th,td { border:1px solid var(--line); padding:.65rem .75rem; text-align:left; vertical-align:top; } th { background:#edf4f7; }
.tree { border-left:2px solid #8fb3c4; margin:1.5rem 0; } .tree div { display:grid; grid-template-columns:minmax(13rem,1fr) 2fr; gap:1rem; border-bottom:1px solid var(--line); padding:.7rem 1rem; } .tree span { color:var(--muted); }
.catalog-list { columns:2; max-width:none; } .site-footer { width:100%; margin:0; padding:1rem 1rem 2rem; color:var(--muted); font-size:.88rem; }
.loader-frame { min-height:60vh; } .loader-heading { display:flex; justify-content:space-between; gap:1rem; align-items:start; } .loading { color:var(--muted); }
@media (max-width:760px) { .site-header__inner { align-items:flex-start; flex-direction:column; gap:.6rem; padding:.6rem; } .primary-nav { align-items:stretch; width:100%; } .nav-group { flex:1 1 9rem; } .nav-group__menu { position:static; min-width:0; margin-top:.25rem; } .page { margin:.5rem 0; padding:0 .3rem; } .page__panel { padding:.75rem; } .tree div { grid-template-columns:1fr; gap:.1rem; } .catalog-list { columns:1; } .loader-heading { flex-direction:column; } .artifact-browser__body { grid-template-columns:1fr; } .artifact-browser__inventory { border-right:0; border-bottom:1px solid var(--line); max-height:16rem; } }
`;
